kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: productdb-pv-claim
  namespace: stage
  labels:
    app: postgres-storage
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: authdb-pv-claim
  namespace: stage
  labels:
    app: postgres-storage
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: orderdb-pv-claim
  namespace: stage
  labels:
    app: postgres-storage
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi