apiVersion: apps/v1
kind: Deployment
metadata:
  name: authdb
  namespace: stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authdb
  template:
    metadata:
      labels:
        app: authdb
    spec:
      containers:
        - name: authdb
          image: postgres:10.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: authdb-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: authdb
      volumes:
        - name: authdb
          persistentVolumeClaim:
            claimName: authdb-pv-claim


---
apiVersion: v1
kind: Service
metadata:
  name: authdb
  namespace: stage
  labels:
    app: authdb
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: authdb