# Ref : https://medium.com/hackernoon/how-to-develop-go-grpc-microservices-and-deploy-in-kubernates-5eace0425bf8

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: stage
  labels:
    app: api
    version: v1
spec:
  selector:
    matchLabels:
      app: api
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: api
        version: v1
    spec:
      containers:
        - name: api
          image: chennakt9/api-gateway:1.0.0
          ports:
            - name: api-service
              containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: stage
spec:
  selector:
    app: api
    version: v1
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30080
  type: NodePort