
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
  namespace: stage
  labels:
    app: auth
    version: v1
spec:
  selector:
    matchLabels:
      app: auth
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: auth
        version: v1
    spec:
      containers:
        - name: auth
          image: chennakt9/auth-ms:1.0.0
          ports:
            - name: auth-svc
              containerPort: 50051

---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: stage
spec:
  selector:
    app: auth
    version: v1
  ports:
    - port: 50051
      targetPort: auth-svc