
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-depl
  labels:
    app: order
spec:
  selector:
    matchLabels:
      app: order
  replicas: 1
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: chennakt9/order-ms:1.0.0
          ports:
            - name: order-svc
              containerPort: 50053

---
apiVersion: v1
kind: Service
metadata:
  name: order-svc
spec:
  selector:
    app: order
  ports:
    - port: 50053
      targetPort: order-svc