
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-depl
  namespace: stage
  labels:
    app: order
    version: v1
spec:
  selector:
    matchLabels:
      app: order
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: order
        version: v1
    spec:
      containers:
        - name: order
          image: chennakt9/order-ms:1.0.0
          ports:
            - name: order-svc
              containerPort: 50053

---
apiVersion: v1
kind: Service
metadata:
  name: order-svc
  namespace: stage
spec:
  selector:
    app: order
    version: v1
  ports:
    - port: 50053
      targetPort: order-svc