
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-depl
  labels:
    app: product
spec:
  selector:
    matchLabels:
      app: product
  replicas: 1
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: chennakt9/product-ms:1.0.0
          ports:
            - name: product-svc
              containerPort: 50052

---
apiVersion: v1
kind: Service
metadata:
  name: product-svc
spec:
  selector:
    app: product
  ports:
    - port: 50052
      targetPort: product-svc